version: '3'
services: 
    bot-dev:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        environment: 
            - "TZ=Europe/Vienna"
        stdin_open: true
        tty: true