version: '3'
services: 
    bot:
        build: 
            context: .
            dockerfile: Dockerfile
        environment: 
            - "TZ=Europe/Vienna"
        env_file: 
            - .env
        stdin_open: true
        tty: true