FROM node:alpine

# Needed to set the correct timezone - fixes a time formating problem in TimeSpanFormatter
RUN apk add tzdata

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]