version: '3'
services: 
    bot:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true
        tty: true