name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature/ci-cd

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: serta-dev:latest
  AZURE_CONTAINER_REGISTRY: sertadev.azurecr.io

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Run tests
#         run: |
#           if [ -f docker-compose.test.yml ]; then
#             docker-compose --file docker-compose.test.yml build
#             docker-compose --file docker-compose.test.yml run sut
#           else
#             docker build . --file Dockerfile
#           fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    #needs: test

    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --file Dockerfile --tag $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME .

      - name: Log into registry
        run: echo "${{ secrets.DEV_ACR_PASSWORD }}" | docker login $AZURE_CONTAINER_REGISTRY -u ${{ secrets.DEV_ACR_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME
